name: Perform Mixeway Scan

on: 
  push:
    branches:
      - master

jobs:
  mixeway-scan:
    name: Mixeway Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse HEAD)"
      - name: Prepare Mixeway docker image
        run: |
          docker pull mixeway/scanner:latest
      - name: Run Scan
        run: |
          docker run --rm \
          -e CI=true \
          -v $(pwd):/app \
          -v /var/run/docker.sock:/var/run/docker.sock \
          mixeway/scanner:latest \
          --api-key 67adc7c4-fe03-409e-bd08-760ad4d17146 \
          --project-id 160 \
          --commit-id ${{ steps.vars.outputs.sha_short }} \
          --branch ${{ steps.vars.outputs.branch }}
